/**
 * ⚠️ DO NOT EDIT THIS FILE! ⚠️
 * このファイルを編集しないでください！
 * KHÔNG ĐƯỢC SỬA FILE NÀY!
 *
 * Auto-generated TypeScript types from Omnify schemas.
 * Any manual changes will be OVERWRITTEN on next generation.
 *
 * To modify: Edit the schema YAML file and run: npx omnify generate
 */

// Common Types
export type { LocaleMap, Locale, ValidationRule, DateTimeString, DateString } from '@omnify-base/schemas/common';

// i18n (Internationalization)
export {
  defaultLocale,
  fallbackLocale,
  supportedLocales,
  validationMessages,
  getMessage,
  getMessages,
} from '@omnify-base/schemas/i18n';

// Plugin Enums
export {
  BankAccountType,
  BankAccountTypeValues,
  isBankAccountType,
  getBankAccountTypeLabel,
  getBankAccountTypeExtra,
} from '@omnify-base/enum/BankAccountType';
export {
  Prefecture,
  PrefectureValues,
  isPrefecture,
  getPrefectureLabel,
  getPrefectureExtra,
} from '@omnify-base/enum/Prefecture';
export {
  PrefectureCode,
  PrefectureCodeValues,
  isPrefectureCode,
  getPrefectureCodeLabel,
  getPrefectureCodeExtra,
} from '@omnify-base/enum/PrefectureCode';

// =============================================================================
// SSO Models - Re-export from @famgia/omnify-react-sso
// =============================================================================

export type {
  User,
  UserCreate,
  UserUpdate,
  Role,
  RoleCreate,
  RoleUpdate,
  Permission,
  PermissionCreate,
  PermissionUpdate,
  Branch,
  BranchCreate,
  BranchUpdate,
  Team,
  TeamCreate,
  TeamUpdate,
} from '@famgia/omnify-react-sso';

export {
  userSchemas,
  userCreateSchema,
  userUpdateSchema,
  userI18n,
  getUserLabel,
  getUserFieldLabel,
  getUserFieldPlaceholder,
  roleSchemas,
  roleCreateSchema,
  roleUpdateSchema,
  roleI18n,
  getRoleLabel,
  getRoleFieldLabel,
  getRoleFieldPlaceholder,
  permissionSchemas,
  permissionCreateSchema,
  permissionUpdateSchema,
  permissionI18n,
  getPermissionLabel,
  getPermissionFieldLabel,
  getPermissionFieldPlaceholder,
  branchSchemas,
  branchCreateSchema,
  branchUpdateSchema,
  branchI18n,
  getBranchLabel,
  getBranchFieldLabel,
  getBranchFieldPlaceholder,
  teamSchemas,
  teamCreateSchema,
  teamUpdateSchema,
  teamI18n,
  getTeamLabel,
  getTeamFieldLabel,
  getTeamFieldPlaceholder,
} from '@famgia/omnify-react-sso';

// =============================================================================
// App-specific Models - Add your local schemas here
// =============================================================================

// Example:
// export type { Product, ProductCreate, ProductUpdate } from './Product';
// export { productSchemas, productCreateSchema, ... } from './Product';
